/*
  ==============================================================================

  This file was auto-generated by the Introjucer!

  It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
  */

#include "PluginProcessor.h"
#include "PluginEditor.h"

#include <assert.h>

const float SpeedOfSound = 343.2f; // m/s


//==============================================================================
AudioProcessorWithDelays::AudioProcessorWithDelays()
{
}

AudioProcessorWithDelays::~AudioProcessorWithDelays()
{
}

//==============================================================================
const String AudioProcessorWithDelays::getName() const
{
	return JucePlugin_Name;
}

bool AudioProcessorWithDelays::acceptsMidi() const
{
#if JucePlugin_WantsMidiInput
	return true;
#else
	return false;
#endif
}

bool AudioProcessorWithDelays::producesMidi() const
{
#if JucePlugin_ProducesMidiOutput
	return true;
#else
	return false;
#endif
}

bool AudioProcessorWithDelays::silenceInProducesSilenceOut() const
{
	return false;
}

double AudioProcessorWithDelays::getTailLengthSeconds() const
{
	return 0.0;
}

int AudioProcessorWithDelays::getNumPrograms()
{
	return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
	// so this should be at least 1, even if you're not really implementing programs.
}

int AudioProcessorWithDelays::getCurrentProgram()
{
	return 0;
}

void AudioProcessorWithDelays::setCurrentProgram(int /*index*/)
{
}

const String AudioProcessorWithDelays::getProgramName(int /*index*/)
{
	return String();
}

void AudioProcessorWithDelays::changeProgramName(int /*index*/, const String& /*newName*/)
{
}

//==============================================================================
void AudioProcessorWithDelays::prepareToPlay(double sampleRate, int /*samplesPerBlock*/)
{
	_delayBuffer.resize((size_t)(sampleRate * 0.5), 0.0f); // 500 ms buffer
}

void AudioProcessorWithDelays::releaseResources()
{
	// When playback stops, you can use this as an opportunity to free up any
	// spare memory, etc.
}

void AudioProcessorWithDelays::processBlock(AudioSampleBuffer& buffer, MidiBuffer& /*midiMessages*/)
{
	// In case we have more outputs than inputs, this code clears any output
	// channels that didn't contain input data, (because these aren't
	// guaranteed to be empty - they may contain garbage).
	// I've added this to avoid people getting screaming feedback
	// when they first compile the plugin, but obviously you don't need to
	// this code if your algorithm already fills all the output channels.
	for (int i = getTotalNumInputChannels(); i < getTotalNumOutputChannels(); ++i)
		buffer.clear(i, 0, buffer.getNumSamples());

	std::lock_guard<std::mutex> guard(m_mutex);

	for (int channel = 0; channel < getTotalNumInputChannels(); ++channel)
	{
		if (channel == 0)
		{
			float* channelData = buffer.getWritePointer(channel);
			const int numSamples = buffer.getNumSamples();

			// Delay implementation
			assert(_delayBuffer.size() > (size_t)numSamples);
			assert(_delayBuffer.size() - numSamples > _delayNumSamples);

			memmove(_delayBuffer.data(), _delayBuffer.data() + numSamples, (_delayBuffer.size() - numSamples) * sizeof(float));
			float* currentBlockStartInBuffer = _delayBuffer.data() + _delayBuffer.size() - numSamples;
			memcpy(currentBlockStartInBuffer, channelData, numSamples * sizeof(float));
			memcpy(channelData, currentBlockStartInBuffer - _delayNumSamples, numSamples * sizeof(float));
		}
	}
}

//==============================================================================
bool AudioProcessorWithDelays::hasEditor() const
{
	return true;
}

AudioProcessorEditor* AudioProcessorWithDelays::createEditor()
{
	return new AudioProcessorAudioProcessorEditor(*this);
}

//==============================================================================
void AudioProcessorWithDelays::getStateInformation(MemoryBlock& /*destData*/)
{
	// You should use this method to store your parameters in the memory block.
	// You could do that either as raw data, or use the XML or ValueTree classes
	// as intermediaries to make it easy to save and load complex data.
}

void AudioProcessorWithDelays::setStateInformation(const void* /*data*/, int /*sizeInBytes*/)
{
	// You should use this method to restore your parameters from this memory block,
	// whose contents will have been created by the getStateInformation() call.
}

void AudioProcessorWithDelays::onDelayChanged(double delay)
{
	std::lock_guard<std::mutex> guard(m_mutex);
	_delayMs = (float)delay;
	_delayNumSamples = (uint32_t)(_delayMs * getSampleRate() / 1000.0f);
}

double AudioProcessorWithDelays::delay() const
{
	return (double)_delayMs;
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
	return new AudioProcessorWithDelays();
}
